### ISSUE TITLE
SIGABRT in get_control_node

### ISSUE THREAD

**Issue by ryzhyk** [p4lang/behavioral-model#125]
simple_switch crashes on the following input (note, the program has been trimmed down to demonstrate the bug)

```
header_type intrinsic_metadata_t {
    fields {
        mgid : 4;
    }
}

header_type eth_t {
    fields {
        dstAddr : 48;
        srcAddr : 48;
        etherType : 16;
    }
}

header_type vlan_tag_t {
    fields {
        tag : 16;
        etherType : 16;
    }
}

header_type ipv4_t {
    fields {
        version : 4;
        ihl : 4;
        diffserv : 8;
        totalLen : 16;
        identification : 16;
        flags : 3;
        fragOffset : 13;
        ttl : 8;
        protocol : 8;
        hdrChecksum : 16;
        src_ip3 : 8;
        src_ip2 : 8;
        src_ip1 : 8;
        src_ip0 : 8;
        dst_ip3 : 8;
        dst_ip2 : 8;
        dst_ip1 : 8;
        dst_ip0 : 8;
    }
}
   
metadata intrinsic_metadata_t intrinsic_metadata;
header eth_t eth;
header vlan_tag_t vlan;
header ipv4_t ip4;

parser start {
    return parse_ethernet;
}

#define ETHERTYPE_VLAN 0x8100, 0x9100, 0x9200, 0x9300
#define ETHERTYPE_IPV4 0x0800


parser parse_vlan {
    extract(vlan);
    return select(latest.etherType) {
        ETHERTYPE_IPV4 : parse_ipv4;
    }
}

parser parse_ethernet {
    extract(eth);
    return select(latest.etherType) {
        ETHERTYPE_VLAN : parse_vlan;
        ETHERTYPE_IPV4 : parse_ipv4;
    }
}

parser parse_ipv4 {
    extract(ip4);
    return ingress;
}

action a_set4() {
}
table set4 {
    actions {a_set4;}
}

control ingress {
        if (valid(vlan)) {
                apply(set4);
                if (valid(vlan)) {
                }
        }
        }
```

The problem seems to be triggered by the nested valid() checks in the control program and is related to some violated assumption about control flow graph structure in the compiler.  Here is the stack trace:

```
Core was generated by `/home/l.ryzhyk/projects/cocoon/p4/bmv2/targets/simple_switch/.libs/lt-simple_sw'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f77072e5418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f7709bba9c0 (LWP 23718))]
(gdb) bt
#0  0x00007f77072e5418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f77072e701a in __GI_abort () at abort.c:89
#2  0x00007f7707c2784d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f7707c256b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f7707c25701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f7707c25919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f7707c4e2bf in std::__throw_out_of_range(char const*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00000000004d9615 in std::__detail::_Map_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bm::ControlFlowNode*>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bm::ControlFlowNode*> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::at (this=0x236f348, __k="_condition_1")
    at /usr/include/c++/5/bits/hashtable_policy.h:665
#8  0x00000000004cf01d in std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bm::ControlFlowNode*, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bm::ControlFlowNode*> > >::at (this=0x236f348, __k="_condition_1") at /usr/include/c++/5/bits/unordered_map.h:689
#9  0x00000000004ca5d4 in bm::P4Objects::get_control_node (this=0x236f130, name="_condition_1") at ../../include/bm/bm_sim/P4Objects.h:131
#10 0x00000000004bae8c in bm::P4Objects::<lambda(const Json::Value&)>::operator()(const Json::Value &) const (__closure=0x7ffc4268d280, cfg_next_node=...) at P4Objects.cpp:853
#11 0x00000000004c0faa in bm::P4Objects::init_objects (this=0x236f130, is=0x7ffc4268daa0, lookup_factory=0x956530 <bm::SwitchWContexts::default_lookup_factory>, device_id=27, cxt_id=0, 
    notifications_transport=std::shared_ptr (count 5, weak 0) 0x2375110, required_fields=std::set with 5 elements = {...}, arith_fields=std::set with 15 elements = {...}) at P4Objects.cpp:885
#12 0x000000000051f194 in bm::Context::init_objects (this=0x236ef60, is=0x7ffc4268daa0, lookup_factory=0x956530 <bm::SwitchWContexts::default_lookup_factory>, required_fields=std::set with 5 elements = {...}, 
    arith_fields=std::set with 15 elements = {...}) at context.cpp:512
#13 0x00000000005cacf1 in bm::SwitchWContexts::init_objects (this=0x236ea30, json_path="f10/f10.s27.json", dev_id=27, transport=std::shared_ptr (empty) 0x0) at switch.cpp:92
#14 0x00000000005cb041 in bm::SwitchWContexts::init_from_command_line_options (this=0x236ea30, argc=24, argv=0x7ffc4268e0b8) at switch.cpp:128
#15 0x000000000044b4b7 in main (argc=24, argv=0x7ffc4268e0b8) at main.cpp:34

```

**Comment by antoninbas** [comment]
The P4 compiler frontend is detecting that the condition is useless and removing it:
```
...
p4_conditional_node._condition_1 is unused, removing it
```
However, it seems that it is not updating the HLIR properly (control flow graph). So this is actually a [p4-hlir] (https://github.com/p4lang/p4-hlir) bug. I will look into it. Thanks for reporting this.

**Comment by antoninbas** [comment]
This was fixed in p4-hlir: https://github.com/p4lang/p4-hlir/commit/fe1b917af855f72ce9b10c1358b586bccfa4f474
Thanks again for reporting this

**Comment by ryzhyk** [comment]
Awesome, thanks for the quick fix!
