### ISSUE TITLE
CLI tests failing

### ISSUE THREAD

**Issue by anirudhSK** [p4lang/behavioral-model#262]
When I run make check, most tests seem to pass except the CLI tests. For instance:

ubuntu@ip-172-30-0-252:~/behavioral-model/targets/simple_switch/tests/CLI_tests$ ./table_dump_extra.test 
Traceback (most recent call last):
  File "./run_one_test.py", line 152, in <module>
    main()
  File "./run_one_test.py", line 104, in main
    with open(command_path, "r") as f:
IOError: [Errno 2] No such file or directory: '/testdata/table_dump_extra.in'

It seems like $srcdir isn't being set in ./table_dump_extra.test?

**Comment by anirudhSK** [comment]
$srcdir was a red herring because it is likely set by the Makefile when running make check. The actual problem was in the autogenerated file run_one_test.py, which had a typo in PYTHONPATH. I have opened a PR to fix this issue.
