### ISSUE TITLE
runtime_CLI exits when mc_dump command is used

### ISSUE THREAD

**Issue by karthik-k-github** [p4lang/behavioral-model#342]
I was trying the runtime_CLI python script to dump the multicast related information using the mc_dump command. The runtime_CLI seems to exit with the following backtrace:

RuntimeCmd: mc_dump

MC ENTRIES

mgrp(1)
  -> (L1h=0, rid=0) -> (ports=[1], lags=[])
  -> (L1h=1, rid=1) -> (ports=[2], lags=[])

LAGS
Traceback (most recent call last):
  File "behavioral-model/targets/l2_switch/runtime_CLI", line 2216, in <module>
    main()
  File "behavioral-model/targets/l2_switch/runtime_CLI", line 2213, in main
    RuntimeAPI(args.pre, standard_client, mc_client).cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "behavioral-model/targets/l2_switch/runtime_CLI", line 585, in handle
    return f(*args, **kwargs)
  File "behavioral-model/targets/l2_switch/runtime_CLI", line 1621, in do_mc_dump
    for lag in mc_json["lags"]:
KeyError: 'lags'

Has anyone faced this issue ?

**Comment by karthik-k-github** [comment]
I am not very familiar with the code but tried to debug more, this happens when running l2_switch target which uses SimplePre and hence does not contain lag_entries map in the MCSimplePre classs, hence the server does not add lags in the json. However the mc_client at the CLI tries to access lags in the mc_json which it obtains from the server. Hope i got this right

**Comment by antoninbas** [comment]
Thanks for reporting this issue and taking the time to look at the code. I have opened a pull request for this, which will be merged into master soon.

**Comment by karthik-k-github** [comment]
Thanks for the fix.
