### ISSUE TITLE
when associating a multicast node to a multicast group will show the 'InvalidMcOperation' message

### ISSUE THREAD

**Issue by dannyxx001** [p4lang/behavioral-model#386]
Sorry, I made a stupid mistake for previous problem. The following is the real problem.
When I try to associate a multicast node to a multicast group, the sswitch_CLI will show the following message 'InvalidMcOperation'. Do anyone know how to solve it?

Traceback (most recent call last):
  File "/home/danny/bmv2/targets/simple_switch/sswitch_CLI.py", line 96, in <module>
    main()
  File "/home/danny/bmv2/targets/simple_switch/sswitch_CLI.py", line 93, in main
    SimpleSwitchAPI(args.pre, standard_client, mc_client, sswitch_client).cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/danny/bmv2/tools/runtime_CLI.py", line 585, in handle
    return f(*args, **kwargs)
  File "/home/danny/bmv2/tools/runtime_CLI.py", line 1562, in do_mc_node_associate
    self.mc_client.bm_mc_node_associate(0, mgrp, l1_hdl)
  File "/home/danny/bmv2/tools/bm_runtime/simple_pre_lag/SimplePreLAG.py", line 222, in bm_mc_node_associate
    self.recv_bm_mc_node_associate()
  File "/home/danny/bmv2/tools/bm_runtime/simple_pre_lag/SimplePreLAG.py", line 246, in recv_bm_mc_node_associate
    raise result.ouch
bm_runtime.simple_pre_lag.ttypes.InvalidMcOperation: InvalidMcOperation(code=4)

Thank you.

**Comment by antoninbas** [comment]
I will fix the CLI code so that it does not crash for invalid pre operations anymore (and prints a more useful error message).
In your case it seems that you are providing an incorrect L1 handle, based on the error code which is 4 (https://github.com/p4lang/behavioral-model/blob/master/thrift_src/simple_pre_lag.thrift#L37).

**Comment by antoninbas** [comment]
Actually, there is a mix-up in how error codes are reported, so it is not an incorrect L1 handle. It is more likely to be this "node associate failed, node is already associated"
