### ISSUE TITLE
Question: Is it a problem?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/behavioral-model#434]
When I use the RPC defined in p4runtime.proto to set pipeline config multiple times, it gives an exception, is it a problem? The process is described as follows.

```
Step1: setting pipeline config with simple_router.json and simple_router.proto.txt;
Step2: setting pipeline config with loopback.json and loopback.proto.txt in the same bmv2(without a restart);
Step3: setting pipeline config with simple_router.json and simple_router.proto.tx in the same bmv2(without a restart);
```
Log:
```
P4Runtime SetForwardingPipelineConfig
[21:11:27.657] [bmv2] [D] [thread 19881] [25.0] [cxt 0] Processing packet received on port 1
[21:11:27.657] [bmv2] [D] [thread 19881] [25.0] [cxt 0] Parser 'parser': start
[21:11:27.657] [bmv2] [D] [thread 19881] [25.0] [cxt 0] Parser state 'start' has no switch, going to default next state
[21:11:27.657] [bmv2] [T] [thread 19881] [25.0] [cxt 0] Bytes parsed: 0
[21:11:27.657] [bmv2] [D] [thread 19881] [25.0] [cxt 0] Extracting header 'ethernet'
[21:11:27.657] [bmv2] [D] [thread 19881] [25.0] [cxt 0] Parser state 'parse_ethernet': key is 86dd
[21:11:27.657] [bmv2] [T] [thread 19881] [25.0] [cxt 0] Bytes parsed: 14
[21:11:27.657] [bmv2] [T] [thread 19881] [25.0] [cxt 0] Skipping checksum 'ipv4.hdrChecksum|ipv4_checksum' verification because target field invalid
[21:11:27.657] [bmv2] [D] [thread 19881] [25.0] [cxt 0] Parser 'parser': end
[21:11:27.657] [bmv2] [D] [thread 19881] [25.0] [cxt 0] Pipeline 'ingress': start
[21:11:27.657] [bmv2] [T] [thread 19881] [25.0] [cxt 0] Condition "_condition_0" is false
[21:11:27.657] [bmv2] [D] [thread 19881] [25.0] [cxt 0] Pipeline 'ingress': end
[21:11:27.657] [bmv2] [D] [thread 19881] [25.0] [cxt 0] Egress port is 0
terminate called after throwing an instance of 'std::out_of_range'   ------//After the exception occurs, I can do nothing on it through gRPC channel.
  what():  _Map_base::at
```

**Comment by antoninbas** [comment]
I'm not aware of such an issue. It would be really helpful if you could provide a gdb traceback for the exception. Just start simple_switch_grpc in gdb, and type `catch throw`, then run the program. When you hit the exception, type `bt` and post the backtrace here.

**Comment by dingrui37** [comment]
I will retry the process to get the backtrace.

**Comment by dingrui37** [comment]
Unfortunately， the exception doesn't occur again.
```
Reading symbols from simple_switch_grpc...done.
(gdb) set args --no-p4
(gdb) catch throw 
Catchpoint 1 (throw)
(gdb) run
Starting program: /usr/local/bin/simple_switch_grpc --no-p4
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Thrift port was not specified, will use 9090
Calling target program-options parser
[New Thread 0x7ffff2a0b700 (LWP 31710)]
[New Thread 0x7ffff220a700 (LWP 31711)]
[New Thread 0x7ffff1a09700 (LWP 31712)]
[New Thread 0x7ffff1208700 (LWP 31713)]
[Thread 0x7ffff1a09700 (LWP 31712) exited]
[New Thread 0x7ffff0a07700 (LWP 31714)]
[New Thread 0x7fffebfff700 (LWP 31715)]
[New Thread 0x7fffeb7fe700 (LWP 31716)]
[New Thread 0x7fffeaffd700 (LWP 31717)]
[New Thread 0x7fffea7fc700 (LWP 31718)]
[New Thread 0x7fffe9ffb700 (LWP 31719)]
[New Thread 0x7fffe97fa700 (LWP 31720)]
[New Thread 0x7fffe8ff9700 (LWP 31721)]
[New Thread 0x7fffe87f8700 (LWP 31722)]
[New Thread 0x7fffe7ff7700 (LWP 31723)]
[New Thread 0x7fffe77f6700 (LWP 31724)]
Server listening on 0.0.0.0:50051
[New Thread 0x7fffe6ff5700 (LWP 31725)]
[New Thread 0x7fffe67f4700 (LWP 31734)]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffe5ff3700 (LWP 31735)]
[New Thread 0x7fffe57f2700 (LWP 31736)]
[New Thread 0x7fffe4ff1700 (LWP 31737)]
[New Thread 0x7fffdffff700 (LWP 31738)]
[New Thread 0x7fffdf7fe700 (LWP 31739)]
[New Thread 0x7fffdeffd700 (LWP 31740)]
[New Thread 0x7fffde7fc700 (LWP 31741)]
[New Thread 0x7fffddffb700 (LWP 31742)]
[New Thread 0x7fffdd7fa700 (LWP 31743)]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffdcff9700 (LWP 31744)]
[Thread 0x7fffe5ff3700 (LWP 31735) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffe5ff3700 (LWP 31749)]
[Thread 0x7fffdcff9700 (LWP 31744) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffdcff9700 (LWP 31750)]
[Thread 0x7fffe5ff3700 (LWP 31749) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffe5ff3700 (LWP 31752)]
[Thread 0x7fffdcff9700 (LWP 31750) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffdcff9700 (LWP 31761)]
[Thread 0x7fffe5ff3700 (LWP 31752) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffe5ff3700 (LWP 31764)]
[Thread 0x7fffdcff9700 (LWP 31761) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffdcff9700 (LWP 31766)]
[Thread 0x7fffe5ff3700 (LWP 31764) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffe5ff3700 (LWP 31767)]
[Thread 0x7fffdcff9700 (LWP 31766) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffdcff9700 (LWP 31780)]
[Thread 0x7fffe5ff3700 (LWP 31767) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffe5ff3700 (LWP 31783)]
[Thread 0x7fffdcff9700 (LWP 31780) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffdcff9700 (LWP 31786)]
[Thread 0x7fffe5ff3700 (LWP 31783) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffe5ff3700 (LWP 31793)]
[Thread 0x7fffdcff9700 (LWP 31786) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffdcff9700 (LWP 31797)]
[Thread 0x7fffe5ff3700 (LWP 31793) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffe5ff3700 (LWP 31799)]
[Thread 0x7fffdcff9700 (LWP 31797) exited]
P4Runtime SetForwardingPipelineConfig
[New Thread 0x7fffdcff9700 (LWP 31803)]
[Thread 0x7fffe5ff3700 (LWP 31799) exited]
```

**Comment by antoninbas** [comment]
You are not running it with the same arguments and in the same conditions. Try with `--log-console` and with packets going through.

**Comment by dingrui37** [comment]
The exception occurs again, but I still cannot get backtrace, because when I use gdb, perhaps it did't occur.

```
[17:35:48.713] [bmv2] [D] [thread 5810] [30.0] [cxt 0] Transmitting packet of size 107 out of port 1
P4Runtime SetForwardingPipelineConfig
[17:35:57.978] [bmv2] [D] [thread 5801] Set default entry for table 't_redirect': redirect - 
[17:36:42.267] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Processing packet received on port 1
[17:36:42.268] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Parser 'parser': start
[17:36:42.268] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Parser state 'start' has no switch, going to default next state
[17:36:42.268] [bmv2] [T] [thread 5805] [31.0] [cxt 0] Bytes parsed: 0
[17:36:42.268] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Parser 'parser': end
[17:36:42.268] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Pipeline 'ingress': start
[17:36:42.268] [bmv2] [T] [thread 5805] [31.0] [cxt 0] Applying table 't_redirect'
[17:36:42.268] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Looking up key:

[17:36:42.268] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Table 't_redirect': miss
[17:36:42.268] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Action entry is redirect - 
[17:36:42.268] [bmv2] [T] [thread 5805] [31.0] [cxt 0] Action redirect
[17:36:42.268] [bmv2] [T] [thread 5805] [31.0] [cxt 0] Primitive (no source info)
[17:36:42.268] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Pipeline 'ingress': end
[17:36:42.268] [bmv2] [D] [thread 5805] [31.0] [cxt 0] Egress port is 64
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
```

**Comment by antoninbas** [comment]
You can try running it under Valgrind to check if you get any memory errors.
Otherwise you will need to provide me with some steps to reproduce the issue.

**Comment by dingrui37** [comment]
When I add a member to action profile ,  I get an exception and the backtrace is shown below. 
I will check the message body, because the params are empty. Afrer the exception occurs, the connection is
terminated by the gRPC server.  I think no exception should occur in the server due to incorrect messages.

```
16:05:22.151925 IP 10.42.94.144.53104 > 10.42.94.144.50051: Flags [P.], seq 23864:23941, ack 249, win 88, options [nop,nop,TS val 1574321299 ecr 1574218919], length 77
16:05:22.152125 IP 10.42.94.144.50051 > 10.42.94.144.53104: Flags [P.], seq 249:270, ack 23941, win 597, options [nop,nop,TS val 1574321299 ecr 1574321299], length 21
16:05:22.152140 IP 10.42.94.144.53104 > 10.42.94.144.50051: Flags [.], ack 270, win 88, options [nop,nop,TS val 1574321299 ecr 1574321299], length 0
16:05:22.154780 IP 10.42.94.144.53104 > 10.42.94.144.50051: Flags [P.], seq 23941:23950, ack 270, win 88, options [nop,nop,TS val 1574321300 ecr 1574321299], length 9
16:05:22.196956 IP 10.42.94.144.50051 > 10.42.94.144.53104: Flags [.], ack 23950, win 597, options [nop,nop,TS val 1574321311 ecr 1574321300], length 0
16:05:22.330040 IP 10.42.94.144.50051 > 10.42.94.144.53104: Flags [R.], seq 270, ack 23950, win 597, options [nop,nop,TS val 1574321344 ecr 1574321300], length 0  
                                                                   / \
                                                                    |     
                                                                    ---- tcp RST  from server
```





```
P4Runtime Write
updates {
  type: INSERT
  entity {
    action_profile_member {
      action_profile_id: 285256676
      member_id: 1000
      action {
        action_id: 16828093
        params {
        }
      }
    }
  }
}

Thread 18 "simple_switch_g" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe67f4700 (LWP 14662)]
pi_p4info_action_param_bitwidth (p4info=p4info@entry=0x7fffe0008450, action_id=<optimized out>, param_id=0) at p4info/actions.c:252
252	  return get_param_data_at(action, param_id)->bitwidth;
(gdb) bt
#0  pi_p4info_action_param_bitwidth (p4info=p4info@entry=0x7fffe0008450, action_id=<optimized out>, param_id=0) at p4info/actions.c:252
#1  0x00007ffff64a3f5c in pi::fe::proto::validate_action_data (p4info=0x7fffe0008450, action=...) at src/action_helpers.cpp:49
#2  0x00007ffff64a229f in pi::fe::proto::ActionProfMgr::validate_action (this=this@entry=0x7fffe00422a0, action=...) at src/action_prof_mgr.cpp:272
#3  0x00007ffff64a2492 in pi::fe::proto::ActionProfMgr::member_create (this=0x7fffe00422a0, member=..., session=...) at src/action_prof_mgr.cpp:111
#4  0x00007ffff649c918 in pi::fe::proto::DeviceMgrImp::action_profile_member_write (session=..., member=..., update=p4::Update_Type_INSERT, this=0x7fffe0008260) at src/device_mgr.cpp:628
#5  pi::fe::proto::DeviceMgrImp::write (this=0x7fffe0008260, request=...) at src/device_mgr.cpp:234
#6  0x00007ffff6499e10 in pi::fe::proto::DeviceMgr::write (this=<optimized out>, request=...) at src/device_mgr.cpp:1232
#7  0x00007ffff66b85f5 in (anonymous namespace)::P4RuntimeServiceImpl::Write (this=<optimized out>, context=<optimized out>, request=0x7fffe67f2d40, rep=<optimized out>) at pi_server.cpp:160
#8  0x00007ffff482c368 in std::_Mem_fn_base<grpc::Status (p4::P4Runtime::Service::*)(grpc::ServerContext*, p4::WriteRequest const*, p4::WriteResponse*), true>::operator()<grpc::ServerContext*, p4::WriteRequest const*, p4::WriteResponse*, void>(p4::P4Runtime::Service*, grpc::ServerContext*&&, p4::WriteRequest const*&&, p4::WriteResponse*&&) const (__object=<optimized out>, this=<optimized out>)
    at /usr/include/c++/5/functional:600
#9  std::_Function_handler<grpc::Status (p4::P4Runtime::Service*, grpc::ServerContext*, p4::WriteRequest const*, p4::WriteResponse*), std::_Mem_fn<grpc::Status (p4::P4Runtime::Service::*)(grpc::ServerContext*, p4::WriteRequest const*, p4::WriteResponse*)> >::_M_invoke(std::_Any_data const&, p4::P4Runtime::Service*&&, grpc::ServerContext*&&, p4::WriteRequest const*&&, p4::WriteResponse*&&) (
    __functor=..., __args#0=<optimized out>, __args#1=<optimized out>, __args#2=<optimized out>, __args#3=<optimized out>) at /usr/include/c++/5/functional:1857
#10 0x00007ffff4835375 in std::function<grpc::Status (p4::P4Runtime::Service*, grpc::ServerContext*, p4::WriteRequest const*, p4::WriteResponse*)>::operator()(p4::P4Runtime::Service*, grpc::ServerContext*, p4::WriteRequest const*, p4::WriteResponse*) const (__args#3=0x7fffe67f2d20, __args#2=0x7fffe67f2d40, __args#1=0x7fffe67f3090, __args#0=0x8413b0, this=0x8235b8)
    at /usr/include/c++/5/functional:2267
#11 grpc::RpcMethodHandler<p4::P4Runtime::Service, p4::WriteRequest, p4::WriteResponse>::RunHandler (this=0x8235b0, param=...) at /usr/local/include/grpc++/impl/codegen/method_handler_impl.h:59
#12 0x00007ffff5b670ba in ?? () from /usr/local/lib/libgrpc++.so.1
#13 0x00007ffff5b6918b in grpc::ThreadManager::MainWorkLoop() () from /usr/local/lib/libgrpc++.so.1
#14 0x00007ffff5b6924c in grpc::ThreadManager::WorkerThread::Run() () from /usr/local/lib/libgrpc++.so.1
#15 0x00007ffff562ec80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007ffff58ff6ba in start_thread (arg=0x7fffe67f4700) at pthread_create.c:333
#17 0x00007ffff4d943dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
